<a href="https://colab.research.google.com/github/Nimalnix/Deep-Learning/blob/main/Matrix_math_exercise_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

**Solution 1: Convert USD revenues to INR**

In [3]:
revenue_usd=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue_inr=75*revenue_usd
revenue_usd

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [4]:
revenue_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

**Solution 2: Calculate total flowers sale every month for divine flowers shop**

In [5]:
unit_sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit=np.array([20,30,15])

In [6]:
total_sales_amount=np.dot(price_per_unit,unit_sold)
total_sales_amount

array([1900, 2640, 1430])